### ISSUE TITLE
Loop start tick in download file incorrectly written for some songs

### ISSUE THREAD

**Issue by chenxi050402** [OpenNBS/NoteBlockWorld#17]
Song tested: https://noteblock.world/song/VVqoH60t8X
Original file: tick 480
Website displays: tick 480
Downloaded file: tick 224

**Comment by Bentroen** [comment]
Caused by https://github.com/OpenNBS/nbs.js/issues/11, fixed by upgrading `nbs.js` to 5.0.1.

**Comment by Bentroen** [comment]
5.0.1 introduced another bug that writes an extra byte at the end of the header, causing NBS to crash. Reopening as the commit above has been reverted in 21caf7d04e4b94528b2fd8138c17c631b4ae28ea.
